env_config: {
  starts:     [0, 0],
  targets:    [3, 0],
  obstacles:  [1, 1],
  max_timesteps: 100,
}

training_config: {
  n_training_steps: 1_000_000,
  n_eval_episodes:    5,
  eval_freq:          100_000,
  deterministic_eval: True,
  render:             False,
}

model_kwargs: {
  learning_rate:              0.001,
  buffer_size:                1_000_000,
  learning_starts:            50_000,
  batch_size:                 32,
  tau:                        1.0,
  gamma:                      0.99,
  train_freq:                 4,
  gradient_steps:             1,
  exploration_fraction:       0.1,
  exploration_initial_eps:    1.0,
  exploration_final_eps:      0.05,
  max_grad_norm:              10.0,
  seed:                       Null,
  verbose:                    2,
  #device:                     'auto',
  device:                    'cuda',
}

logdir: "test_logs"
