env_config: {
  starts:     [0, 0,
               3, 0,
               3, 3],
  targets:    [3, 0,
               0, 0,
               0, 3],
  obstacles:  [1, 1],
  max_timesteps: 100,
}

training_config: {
  n_training_steps: 1000000,
  n_eval_episodes:    1,
  eval_freq:          10000,
  deterministic_eval: True,
  render:             False,
}

model_kwargs: {
  learning_rate:              0.0001,
  buffer_size:                1000000,
  learning_starts:            50000,
  batch_size:                 32,
  tau:                        1.0,
  gamma:                      0.99,
  train_freq:                 4,
  gradient_steps:             1,
  exploration_fraction:       0.1,
  exploration_initial_eps:    1.0,
  exploration_final_eps:      0.05,
  max_grad_norm:              10.0,
  seed:                       Null,
  verbose:                    2,
}
